export const PLATE_REGIONS = [
  // Metros (only Dhaka & Chattogram)
  "Dhaka Metro",
  "Chattogram Metro",
  // Divisions & Districts
  "Dhaka",
  "Chattogram",
  "Rajshahi",
  "Khulna",
  "Sylhet",
  "Barishal",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Gazipur",
  "Narayanganj",
  "Tangail",
  "Faridpur",
  "Manikganj",
  "Munshiganj",
  "Gopalganj",
  "Kishoreganj",
  "Narsingdi",
  "Shariatpur",
  "Madaripur",
  "Rajbari",
  "Netrokona",
  "Jamalpur",
  "Sherpur",
  "Cox's Bazar",
  "Rangamati",
  "Bandarban",
  "Khagrachhari",
  "Feni",
  "Lakshmipur",
  "Noakhali",
  "Chandpur",
  "Brahmanbaria",
  "Bogura",
  "Pabna",
  "Naogaon",
  "Natore",
  "Sirajganj",
  "Chapainawabganj",
  "Joypurhat",
  "Jessore",
  "Satkhira",
  "Jhenaidah",
  "Narail",
  "Kushtia",
  "Meherpur",
  "Chuadanga",
  "Magura",
  "Bagerhat",
  "Habiganj",
  "Moulvibazar",
  "Sunamganj",
  "Patuakhali",
  "Pirojpur",
  "Bhola",
  "Jhalokati",
  "Barguna",
  "Dinajpur",
  "Thakurgaon",
  "Panchagarh",
  "Nilphamari",
  "Kurigram",
  "Lalmonirhat",
  "Gaibandha",
] as const;

// English → Bangla mapping for converting display plateNumber back to Bangla
// Longest first to avoid partial match (e.g. "Dhaka Metro" before "Dhaka")
export const ENGLISH_TO_BANGLA_REGION: [string, string][] = [
  ["Dhaka Metro", "ঢাকা মেট্রো"],
  ["Chattogram Metro", "চট্টগ্রাম মেট্রো"],
  ["Narayanganj", "নারায়ণগঞ্জ"],
  ["Chapainawabganj", "চাঁপাইনবাবগঞ্জ"],
  ["Brahmanbaria", "ব্রাহ্মণবাড়িয়া"],
  ["Moulvibazar", "মৌলভীবাজার"],
  ["Lalmonirhat", "লালমনিরহাট"],
  ["Khagrachhari", "খাগড়াছড়ি"],
  ["Kishoreganj", "কিশোরগঞ্জ"],
  ["Patuakhali", "পটুয়াখালী"],
  ["Chuadanga", "চুয়াডাঙ্গা"],
  ["Nilphamari", "নীলফামারী"],
  ["Mymensingh", "ময়মনসিংহ"],
  ["Shariatpur", "শরীয়তপুর"],
  ["Joypurhat", "জয়পুরহাট"],
  ["Sunamganj", "সুনামগঞ্জ"],
  ["Thakurgaon", "ঠাকুরগাঁও"],
  ["Sirajganj", "সিরাজগঞ্জ"],
  ["Chattogram", "চট্টগ্রাম"],
  ["Gopalganj", "গোপালগঞ্জ"],
  ["Noakhali", "নোয়াখালী"],
  ["Lakshmipur", "লক্ষ্মীপুর"],
  ["Cox's Bazar", "কক্সবাজার"],
  ["Manikganj", "মানিকগঞ্জ"],
  ["Munshiganj", "মুন্সীগঞ্জ"],
  ["Kurigram", "কুড়িগ্রাম"],
  ["Gaibandha", "গাইবান্ধা"],
  ["Rangamati", "রাঙ্গামাটি"],
  ["Pirojpur", "পিরোজপুর"],
  ["Madaripur", "মাদারীপুর"],
  ["Satkhira", "সাতক্ষীরা"],
  ["Jhalokati", "ঝালকাঠি"],
  ["Narsingdi", "নরসিংদী"],
  ["Faridpur", "ফরিদপুর"],
  ["Dinajpur", "দিনাজপুর"],
  ["Meherpur", "মেহেরপুর"],
  ["Bandarban", "বান্দরবান"],
  ["Habiganj", "হবিগঞ্জ"],
  ["Netrokona", "নেত্রকোনা"],
  ["Jamalpur", "জামালপুর"],
  ["Jhenaidah", "ঝিনাইদহ"],
  ["Bagerhat", "বাগেরহাট"],
  ["Panchagarh", "পঞ্চগড়"],
  ["Tangail", "টাঙ্গাইল"],
  ["Rajshahi", "রাজশাহী"],
  ["Rajbari", "রাজবাড়ী"],
  ["Kushtia", "কুষ্টিয়া"],
  ["Comilla", "কুমিল্লা"],
  ["Gazipur", "গাজীপুর"],
  ["Barishal", "বরিশাল"],
  ["Chandpur", "চাঁদপুর"],
  ["Barguna", "বরগুনা"],
  ["Sherpur", "শেরপুর"],
  ["Narail", "নড়াইল"],
  ["Magura", "মাগুরা"],
  ["Rangpur", "রংপুর"],
  ["Sylhet", "সিলেট"],
  ["Khulna", "খুলনা"],
  ["Bogura", "বগুড়া"],
  ["Pabna", "পাবনা"],
  ["Naogaon", "নওগাঁ"],
  ["Natore", "নাটোর"],
  ["Jessore", "যশোর"],
  ["Bhola", "ভোলা"],
  ["Feni", "ফেনী"],
  ["Dhaka", "ঢাকা"],
];

// Bangla → English mapping (longest first to avoid partial match)
// Used by normalizePlate so OCR Bangla and manual English produce the same ID
export const BANGLA_TO_ENGLISH_REGION: [string, string][] = [
  // Metros first (longer, must match before bare city names)
  ["ঢাকা মেট্রো", "dhaka metro"],
  ["চট্টগ্রাম মেট্রো", "chattogram metro"],
  // Districts / Divisions
  ["নারায়ণগঞ্জ", "narayanganj"],
  ["চাঁপাইনবাবগঞ্জ", "chapainawabganj"],
  ["ব্রাহ্মণবাড���িয়া", "brahmanbaria"],
  ["মৌলভীবাজার", "moulvibazar"],
  ["লালমনিরহাট", "lalmonirhat"],
  ["খাগড়াছড়ি", "khagrachhari"],
  ["কিশোরগঞ্জ", "kishoreganj"],
  ["পটুয়াখালী", "patuakhali"],
  ["চুয়াডাঙ্গা", "chuadanga"],
  ["নীলফামারী", "nilphamari"],
  ["ময়মনসিংহ", "mymensingh"],
  ["শরীয়তপুর", "shariatpur"],
  ["জয়পুরহাট", "joypurhat"],
  ["সুনামগঞ্জ", "sunamganj"],
  ["ঠাকুরগাঁও", "thakurgaon"],
  ["সিরাজগঞ্জ", "sirajganj"],
  ["চট্টগ্রাম", "chattogram"],
  ["গোপালগঞ্জ", "gopalganj"],
  ["নোয়াখালী", "noakhali"],
  ["লক���ষ্মীপ��র", "lakshmipur"],
  ["কক্সবাজার", "coxs bazar"],
  ["মানিকগঞ্জ", "manikganj"],
  ["মুন্সীগঞ্জ", "munshiganj"],
  ["কুড়িগ্রাম", "kurigram"],
  ["গাইবান্ধা", "gaibandha"],
  ["রাঙ্গামাটি", "rangamati"],
  ["পিরোজপুর", "pirojpur"],
  ["মাদারীপুর", "madaripur"],
  ["সাতক্ষীরা", "satkhira"],
  ["ঝালকাঠি", "jhalokati"],
  ["নরসিংদী", "narsingdi"],
  ["ফরিদপুর", "faridpur"],
  ["দিনাজপুর", "dinajpur"],
  ["মেহেরপুর", "meherpur"],
  ["বান্দরবান", "bandarban"],
  ["হবিগঞ্জ", "habiganj"],
  ["নেত্রকোনা", "netrokona"],
  ["জামালপুর", "jamalpur"],
  ["ঝিনাইদহ", "jhenaidah"],
  ["বাগেরহাট", "bagerhat"],
  ["পঞ্চগড়", "panchagarh"],
  ["টাঙ্গাইল", "tangail"],
  ["রাজশাহী", "rajshahi"],
  ["রাজবাড়���", "rajbari"],
  ["কুষ্টিয়া", "kushtia"],
  ["কুমিল্লা", "comilla"],
  ["গাজীপুর", "gazipur"],
  ["বরিশাল", "barishal"],
  ["চাঁদপুর", "chandpur"],
  ["বরগুনা", "barguna"],
  ["শেরপুর", "sherpur"],
  ["নড়াইল", "narail"],
  ["মাগুরা", "magura"],
  ["রংপুর", "rangpur"],
  ["সিলেট", "sylhet"],
  ["খুলনা", "khulna"],
  ["বগুড়া", "bogura"],
  ["পাবনা", "pabna"],
  ["নওগাঁ", "naogaon"],
  ["নাটোর", "natore"],
  ["যশোর", "jessore"],
  ["ভোলা", "bhola"],
  ["ফেনী", "feni"],
  ["ঢাকা", "dhaka"],
];
