export const PLATE_REGIONS = [
  // Metros (only Dhaka & Chattogram)
  "Dhaka Metro",
  "Chattogram Metro",
  // Divisions & Districts
  "Dhaka",
  "Chattogram",
  "Rajshahi",
  "Khulna",
  "Sylhet",
  "Barishal",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Gazipur",
  "Narayanganj",
  "Tangail",
  "Faridpur",
  "Manikganj",
  "Munshiganj",
  "Gopalganj",
  "Kishoreganj",
  "Narsingdi",
  "Shariatpur",
  "Madaripur",
  "Rajbari",
  "Netrokona",
  "Jamalpur",
  "Sherpur",
  "Cox's Bazar",
  "Rangamati",
  "Bandarban",
  "Khagrachhari",
  "Feni",
  "Lakshmipur",
  "Noakhali",
  "Chandpur",
  "Brahmanbaria",
  "Bogura",
  "Pabna",
  "Naogaon",
  "Natore",
  "Sirajganj",
  "Chapainawabganj",
  "Joypurhat",
  "Jessore",
  "Satkhira",
  "Jhenaidah",
  "Narail",
  "Kushtia",
  "Meherpur",
  "Chuadanga",
  "Magura",
  "Bagerhat",
  "Habiganj",
  "Moulvibazar",
  "Sunamganj",
  "Patuakhali",
  "Pirojpur",
  "Bhola",
  "Jhalokati",
  "Barguna",
  "Dinajpur",
  "Thakurgaon",
  "Panchagarh",
  "Nilphamari",
  "Kurigram",
  "Lalmonirhat",
  "Gaibandha",
] as const;

// Bangla → English mapping (longest first to avoid partial match)
// Used by normalizePlate so OCR Bangla and manual English produce the same ID
export const BANGLA_TO_ENGLISH_REGION: [string, string][] = [
  // Metros first (longer, must match before bare city names)
  ["ঢাকা মেট্রো", "dhaka metro"],
  ["চট্টগ্রাম মেট্রো", "chattogram metro"],
  // Districts / Divisions
  ["নারায়ণগঞ্জ", "narayanganj"],
  ["চাঁপাইনবাবগঞ্জ", "chapainawabganj"],
  ["ব্রাহ্মণবাড���িয়া", "brahmanbaria"],
  ["মৌলভীবাজার", "moulvibazar"],
  ["লালমনিরহাট", "lalmonirhat"],
  ["খাগড়াছড়ি", "khagrachhari"],
  ["কিশোরগঞ্জ", "kishoreganj"],
  ["পটুয়াখালী", "patuakhali"],
  ["চুয়াডাঙ্গা", "chuadanga"],
  ["নীলফামারী", "nilphamari"],
  ["ময়মনসিংহ", "mymensingh"],
  ["শরীয়তপুর", "shariatpur"],
  ["জয়পুরহাট", "joypurhat"],
  ["সুনামগঞ্জ", "sunamganj"],
  ["ঠাকুরগাঁও", "thakurgaon"],
  ["সিরাজগঞ্জ", "sirajganj"],
  ["চট্টগ্রাম", "chattogram"],
  ["গোপালগঞ্জ", "gopalganj"],
  ["নোয়াখালী", "noakhali"],
  ["লক���ষ্মীপ��র", "lakshmipur"],
  ["কক্সবাজার", "coxs bazar"],
  ["মানিকগঞ্জ", "manikganj"],
  ["মুন্সীগঞ্জ", "munshiganj"],
  ["কুড়িগ্রাম", "kurigram"],
  ["গাইবান্ধা", "gaibandha"],
  ["রাঙ্গামাটি", "rangamati"],
  ["পিরোজপুর", "pirojpur"],
  ["মাদারীপুর", "madaripur"],
  ["সাতক্ষীরা", "satkhira"],
  ["ঝালকাঠি", "jhalokati"],
  ["নরসিংদী", "narsingdi"],
  ["ফরিদপুর", "faridpur"],
  ["দিনাজপুর", "dinajpur"],
  ["মেহেরপুর", "meherpur"],
  ["বান্দরবান", "bandarban"],
  ["হবিগঞ্জ", "habiganj"],
  ["নেত্রকোনা", "netrokona"],
  ["জামালপুর", "jamalpur"],
  ["ঝিনাইদহ", "jhenaidah"],
  ["বাগেরহাট", "bagerhat"],
  ["পঞ্চগড়", "panchagarh"],
  ["টাঙ্গাইল", "tangail"],
  ["রাজশাহী", "rajshahi"],
  ["রাজবাড়���", "rajbari"],
  ["কুষ্টিয়া", "kushtia"],
  ["কুমিল্লা", "comilla"],
  ["গাজীপুর", "gazipur"],
  ["বরিশাল", "barishal"],
  ["চাঁদপুর", "chandpur"],
  ["বরগুনা", "barguna"],
  ["শেরপুর", "sherpur"],
  ["নড়াইল", "narail"],
  ["মাগুরা", "magura"],
  ["রংপুর", "rangpur"],
  ["সিলেট", "sylhet"],
  ["খুলনা", "khulna"],
  ["বগুড়া", "bogura"],
  ["পাবনা", "pabna"],
  ["নওগাঁ", "naogaon"],
  ["নাটোর", "natore"],
  ["যশোর", "jessore"],
  ["ভোলা", "bhola"],
  ["ফেনী", "feni"],
  ["ঢাকা", "dhaka"],
];
